### ISSUE TITLE
巡检报告问题反馈

### ISSUE THREAD

**Issue by yzb420** [ddcw/inspection#1]
尊敬的楼主好，我这边使用2.1版本后发现一直卡在巡检中，无法生成报告，之前1.2版本是没有这些问题的。
![image](https://user-images.githubusercontent.com/102197195/183270871-ba65eb7d-a09f-4c3f-a5bd-251ee11444b7.png)
我给楼主提个建议就是把巡检服务器和数据库分开这样似乎能好点。

**Comment by ddcw** [comment]
请看下报错(启动控制台的窗口),  <主机信息巡检完成> 之后是生成巡检报告,  推测为jinja2的报错, 因为巡检报告的界面有部分功能我没有做判断(xx['status']).
巡检脚本支持远程巡检的呢, 你说的 "把巡检服务器和数据库分开" 能详细说下吗

**Comment by yzb420** [comment]
感谢楼解答我的问题，巡检服务器和数据库分开是指单独巡检数据库和Linux服务，现在咱们一键巡检，里面包括数据库+服务器都在一个报告里，因此咱们可以搞两个按钮来实现，按钮1：数据库巡检  按钮2：服务器巡检

**Comment by ddcw** [comment]
因为巡检主机的时候 会 依赖部分数据库信息(主要是那几个目录和日志文件,), 所以整合到一起的.
但是主机巡检是可以手动禁止的.  配置文件(conf/conf.yaml)里面有个参数 Enable_Shell 的值改为False, 就不会巡检主机信息.( inspection/ddcw_inspection.py 第314行有做判断)

**Comment by yzb420** [comment]
好的，非常感谢楼主，没有做判断(xx['status']).这个问题楼主会修复此问题吗

**Comment by ddcw** [comment]
会修复,  目前的巡检项目并没有全部展示到html(可查看html源码,注释部分,只是原始数据), 原因如下:  
1. 有部分巡检项还有待争议(比如已经取消了max_allowed_packet参数检查),   
2. 量太多   
3. 还没想好前端界面 怎样排版好看.....  
4. 告警程度 部分后面会细分(目前只有 正常, Warning, Error 3个级别, 扣分标准默认分别是1,   0.3 和 0, 太粗糙了)
