### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by cf157290** [ddcw/inspection#7]
版本v2.2
![image](https://github.com/ddcw/inspection/assets/52031530/4f8106fa-4bb8-433a-b15b-ef9a1da3020d)
执行到这儿就报错了，此时巡检中和巡检完成也无法正常显示
![image](https://github.com/ddcw/inspection/assets/52031530/2ae01eb6-828d-48ea-aa51-7614ce03b08d)
![image](https://github.com/ddcw/inspection/assets/52031530/16f0de2a-faf1-4a6d-9f9e-5e1845e8c980)
![image](https://github.com/ddcw/inspection/assets/52031530/669f6bf6-e890-4655-be70-6e94a37cbc26)

**Comment by ddcw** [comment]
> 版本v2.2 ![image](https://private-user-images.githubusercontent.com/52031530/285794456-4f8106fa-4bb8-433a-b15b-ef9a1da3020d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzY5NDIsIm5iZiI6MTcwMTA3NjY0MiwicGF0aCI6Ii81MjAzMTUzMC8yODU3OTQ0NTYtNGY4MTA2ZmEtNGJiOC00MzNhLWIxNWItZWY5YTFkYTMwMjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA5MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ODRiYTg4ZTgxY2VkMTAzMjM3N2UwZTA3ZDE5NzRmZTk2NmYxNGQzMTJlY2UzNzQ1MmU4ZDA1MWNmMjViN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16nKqn7ObWeV6q5AJrRwqamQQodClk5rhwL73eI6OGk) 执行到这儿就报错了，此时巡检中和巡检完成也无法正常显示 ![image](https://private-user-images.githubusercontent.com/52031530/285795015-2ae01eb6-828d-48ea-aa51-7614ce03b08d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzY5NDIsIm5iZiI6MTcwMTA3NjY0MiwicGF0aCI6Ii81MjAzMTUzMC8yODU3OTUwMTUtMmFlMDFlYjYtODI4ZC00OGVhLWFhNTEtNzYxNGNlMDNiMDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA5MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyOTBkN2JlMWQwZmY2YTcwYmUzNjhlNGEwYzZiNzAwNjI2YThlMjhhOGYwYzgwMTI1YTcxMWYzZjgwN2JmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1TzBIrYMl9kfJNpbF-viODKaEGLvLqojPmDOGo0wDlQ) ![image](https://private-user-images.githubusercontent.com/52031530/285795112-16f0de2a-faf1-4a6d-9f9e-5e1845e8c980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzY5NDIsIm5iZiI6MTcwMTA3NjY0MiwicGF0aCI6Ii81MjAzMTUzMC8yODU3OTUxMTItMTZmMGRlMmEtZmFmMS00YTZkLTlmOWUtNWUxODQ1ZThjOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA5MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNGY1ZjI2Y2U3NjY4ZGJiM2MxMmIzNWRiMjI3NjMyOTEwNGU5ZjQ0YWExYmU4MWFiZmQ4YmFiNDVmZWMwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TzECr-xWV_vKOgUFS4l9w7deJFj8iFKpOI92nTNa2WU) ![image](https://private-user-images.githubusercontent.com/52031530/285795287-669f6bf6-e890-4655-be70-6e94a37cbc26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzY5NDIsIm5iZiI6MTcwMTA3NjY0MiwicGF0aCI6Ii81MjAzMTUzMC8yODU3OTUyODctNjY5ZjZiZjYtZTg5MC00NjU1LWJlNzAtNmU5NGEzN2NiYzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA5MTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1M2Q2YmU1Y2MyNDg1MjQ1ZWQ0YzRiNjNjOTg3ODM2ZWUxZWM0NWQxZDA0N2E2ZDhiOGZlM2ExNWQwZWM5OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NsPc4i2X5WYNZ3MjTCRXZP8iwZ6ToIdUyYP61KVKcpc)

从日志来看是巡检Qcache_hits的时候的问题, 8.0已经没得Qcache_hits状态了(`show global status`)
应该不影响html版的巡检报告的生成的,  你看下 **巡检工具目录下的 tmp目录**下面 是否有生成html巡检报告呢

docx版的巡检报告 多等一会(等后台进程超时)看下呢. 也是 tmp目录下面

**Comment by cf157290** [comment]
试了一下确实能生成html，但是docx一直没生成，此时已经执行了将近一小时，刷新页面后巡检中和巡检完成两个页面也无法正常显示，其余页面正常，只能重启项目才能恢复正常

**Comment by ddcw** [comment]
> 试了一下确实能生成html，但是docx一直没生成，此时已经执行了将近一小时，刷新页面后巡检中和巡检完成两个页面也无法正常显示，其余页面正常，只能重启项目才能恢复正常

应该是分析节点关系的那个进程堵住了.
编辑 conf/global.yaml 设置 `node_relation` 为 `False` 然后重启试下呢(html生成后, 大概3分钟后生成docx的)
```conf/global.yaml
node_relation : False
```

注: 本BUG短时间内不会修复 -_-

**Comment by cf157290** [comment]
尝试了一下还是相同的效果，生成不出docx
![image](https://github.com/ddcw/inspection/assets/52031530/44d0bbe2-57fa-4228-bb95-a78adb33df65)

**Comment by ddcw** [comment]
那就不要 docx版的吧, 反正内容和html版的完全一样, 而且排版还很丑.  或者使用其它工具从html转到docx版.
docx版大概如下样式
![image](https://github.com/ddcw/inspection/assets/32298386/34be4f31-2789-4272-851d-29ce64387e03)
![image](https://github.com/ddcw/inspection/assets/32298386/c561ce1f-438b-4ec2-b350-e5f18e612a81)


> 尝试了一下还是相同的效果，生成不出docx ![image](https://private-user-images.githubusercontent.com/52031530/286105959-44d0bbe2-57fa-4228-bb95-a78adb33df65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNDI5NTYsIm5iZiI6MTcwMTE0MjY1NiwicGF0aCI6Ii81MjAzMTUzMC8yODYxMDU5NTktNDRkMGJiZTItNTdmYS00MjI4LWJiOTUtYTc4YWRiMzNkZjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDAzMzczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMmM1ZGY2ZGExNmVmZTRkZTU1MzJlZDZiYjY5ZjE4N2Y2ODQyZWQ2MzU5NzViODNlOGZjN2U5ZDg3NDI4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IUoxQaplOsDV1gzDnPyrmCvAtIlHZN1qT8JGkixLgXU)

**Comment by cf157290** [comment]
好，那先这样用，感谢作者的项目，江湖救急了
